name: 'Service Catalog: Get Payload'
description: 'Gets the payload of a service catalog request'
inputs:
  payload:
    description: 'The payload of the service catalog request'
    required: false
    default: ${{ github.event.client_payload.data }}
  payload_file:
    description: 'The filename to save the payload to'
    required: false
    default: '/tmp/service-catalog-payload.json'
runs:
  using: 'node16'
  main: 'payload.js'
branding:
  icon: 'cloud-snow'
  color: 'orange'